// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kategori_obat.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	kategori_obat.proto

It has these top-level messages:
	AddKategoriObatReq
	ReadKategoriObatByNamaReq
	ReadKategoriObatByNamaResp
	ReadKategoriObatResp
	UpdateKategoriObatReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddKategoriObatReq struct {
	KodeKategoriObat string `protobuf:"bytes,1,opt,name=KodeKategoriObat" json:"KodeKategoriObat,omitempty"`
	NamaKategoriObat string `protobuf:"bytes,2,opt,name=NamaKategoriObat" json:"NamaKategoriObat,omitempty"`
	Deskripsi        string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	KodeObat         string `protobuf:"bytes,4,opt,name=KodeObat" json:"KodeObat,omitempty"`
	CreatedBy        string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn        string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdateBy         string `protobuf:"bytes,7,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
	UpdateOn         string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	Status           int32  `protobuf:"varint,9,opt,name=Status" json:"Status,omitempty"`
}

func (m *AddKategoriObatReq) Reset()                    { *m = AddKategoriObatReq{} }
func (m *AddKategoriObatReq) String() string            { return proto.CompactTextString(m) }
func (*AddKategoriObatReq) ProtoMessage()               {}
func (*AddKategoriObatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddKategoriObatReq) GetKodeKategoriObat() string {
	if m != nil {
		return m.KodeKategoriObat
	}
	return ""
}

func (m *AddKategoriObatReq) GetNamaKategoriObat() string {
	if m != nil {
		return m.NamaKategoriObat
	}
	return ""
}

func (m *AddKategoriObatReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *AddKategoriObatReq) GetKodeObat() string {
	if m != nil {
		return m.KodeObat
	}
	return ""
}

func (m *AddKategoriObatReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddKategoriObatReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddKategoriObatReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *AddKategoriObatReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *AddKategoriObatReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReadKategoriObatByNamaReq struct {
	NamaKategoriObat string `protobuf:"bytes,2,opt,name=NamaKategoriObat" json:"NamaKategoriObat,omitempty"`
}

func (m *ReadKategoriObatByNamaReq) Reset()                    { *m = ReadKategoriObatByNamaReq{} }
func (m *ReadKategoriObatByNamaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKategoriObatByNamaReq) ProtoMessage()               {}
func (*ReadKategoriObatByNamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadKategoriObatByNamaReq) GetNamaKategoriObat() string {
	if m != nil {
		return m.NamaKategoriObat
	}
	return ""
}

type ReadKategoriObatByNamaResp struct {
	KodeKategoriObat string `protobuf:"bytes,1,opt,name=KodeKategoriObat" json:"KodeKategoriObat,omitempty"`
	NamaKategoriObat string `protobuf:"bytes,2,opt,name=NamaKategoriObat" json:"NamaKategoriObat,omitempty"`
	Deskripsi        string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	KodeObat         string `protobuf:"bytes,4,opt,name=KodeObat" json:"KodeObat,omitempty"`
	CreatedBy        string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn        string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdateBy         string `protobuf:"bytes,7,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
	UpdateOn         string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	Status           int32  `protobuf:"varint,9,opt,name=Status" json:"Status,omitempty"`
}

func (m *ReadKategoriObatByNamaResp) Reset()                    { *m = ReadKategoriObatByNamaResp{} }
func (m *ReadKategoriObatByNamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKategoriObatByNamaResp) ProtoMessage()               {}
func (*ReadKategoriObatByNamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadKategoriObatByNamaResp) GetKodeKategoriObat() string {
	if m != nil {
		return m.KodeKategoriObat
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetNamaKategoriObat() string {
	if m != nil {
		return m.NamaKategoriObat
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetKodeObat() string {
	if m != nil {
		return m.KodeObat
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *ReadKategoriObatByNamaResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReadKategoriObatResp struct {
	AllKategoriObat []*ReadKategoriObatByNamaResp `protobuf:"bytes,1,rep,name=allKategoriObat" json:"allKategoriObat,omitempty"`
}

func (m *ReadKategoriObatResp) Reset()                    { *m = ReadKategoriObatResp{} }
func (m *ReadKategoriObatResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKategoriObatResp) ProtoMessage()               {}
func (*ReadKategoriObatResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadKategoriObatResp) GetAllKategoriObat() []*ReadKategoriObatByNamaResp {
	if m != nil {
		return m.AllKategoriObat
	}
	return nil
}

type UpdateKategoriObatReq struct {
	KodeKategoriObat string `protobuf:"bytes,1,opt,name=KodeKategoriObat" json:"KodeKategoriObat,omitempty"`
	NamaKategoriObat string `protobuf:"bytes,2,opt,name=NamaKategoriObat" json:"NamaKategoriObat,omitempty"`
	Deskripsi        string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	KodeObat         string `protobuf:"bytes,4,opt,name=KodeObat" json:"KodeObat,omitempty"`
	CreatedBy        string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn        string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdateBy         string `protobuf:"bytes,7,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
	UpdateOn         string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	Status           int32  `protobuf:"varint,9,opt,name=Status" json:"Status,omitempty"`
}

func (m *UpdateKategoriObatReq) Reset()                    { *m = UpdateKategoriObatReq{} }
func (m *UpdateKategoriObatReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateKategoriObatReq) ProtoMessage()               {}
func (*UpdateKategoriObatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateKategoriObatReq) GetKodeKategoriObat() string {
	if m != nil {
		return m.KodeKategoriObat
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetNamaKategoriObat() string {
	if m != nil {
		return m.NamaKategoriObat
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetKodeObat() string {
	if m != nil {
		return m.KodeObat
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *UpdateKategoriObatReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*AddKategoriObatReq)(nil), "grpc.AddKategoriObatReq")
	proto.RegisterType((*ReadKategoriObatByNamaReq)(nil), "grpc.ReadKategoriObatByNamaReq")
	proto.RegisterType((*ReadKategoriObatByNamaResp)(nil), "grpc.ReadKategoriObatByNamaResp")
	proto.RegisterType((*ReadKategoriObatResp)(nil), "grpc.ReadKategoriObatResp")
	proto.RegisterType((*UpdateKategoriObatReq)(nil), "grpc.UpdateKategoriObatReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for KategoriObatService service

type KategoriObatServiceClient interface {
	AddKategoriObat(ctx context.Context, in *AddKategoriObatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKategoriObatByNama(ctx context.Context, in *ReadKategoriObatByNamaReq, opts ...grpc1.CallOption) (*ReadKategoriObatByNamaResp, error)
	ReadKategoriObat(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKategoriObatResp, error)
	UpdateKategoriObat(ctx context.Context, in *UpdateKategoriObatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type kategoriObatServiceClient struct {
	cc *grpc1.ClientConn
}

func NewKategoriObatServiceClient(cc *grpc1.ClientConn) KategoriObatServiceClient {
	return &kategoriObatServiceClient{cc}
}

func (c *kategoriObatServiceClient) AddKategoriObat(ctx context.Context, in *AddKategoriObatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KategoriObatService/AddKategoriObat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kategoriObatServiceClient) ReadKategoriObatByNama(ctx context.Context, in *ReadKategoriObatByNamaReq, opts ...grpc1.CallOption) (*ReadKategoriObatByNamaResp, error) {
	out := new(ReadKategoriObatByNamaResp)
	err := grpc1.Invoke(ctx, "/grpc.KategoriObatService/ReadKategoriObatByNama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kategoriObatServiceClient) ReadKategoriObat(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKategoriObatResp, error) {
	out := new(ReadKategoriObatResp)
	err := grpc1.Invoke(ctx, "/grpc.KategoriObatService/ReadKategoriObat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kategoriObatServiceClient) UpdateKategoriObat(ctx context.Context, in *UpdateKategoriObatReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KategoriObatService/UpdateKategoriObat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KategoriObatService service

type KategoriObatServiceServer interface {
	AddKategoriObat(context.Context, *AddKategoriObatReq) (*google_protobuf.Empty, error)
	ReadKategoriObatByNama(context.Context, *ReadKategoriObatByNamaReq) (*ReadKategoriObatByNamaResp, error)
	ReadKategoriObat(context.Context, *google_protobuf.Empty) (*ReadKategoriObatResp, error)
	UpdateKategoriObat(context.Context, *UpdateKategoriObatReq) (*google_protobuf.Empty, error)
}

func RegisterKategoriObatServiceServer(s *grpc1.Server, srv KategoriObatServiceServer) {
	s.RegisterService(&_KategoriObatService_serviceDesc, srv)
}

func _KategoriObatService_AddKategoriObat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKategoriObatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KategoriObatServiceServer).AddKategoriObat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KategoriObatService/AddKategoriObat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KategoriObatServiceServer).AddKategoriObat(ctx, req.(*AddKategoriObatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KategoriObatService_ReadKategoriObatByNama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKategoriObatByNamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KategoriObatServiceServer).ReadKategoriObatByNama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KategoriObatService/ReadKategoriObatByNama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KategoriObatServiceServer).ReadKategoriObatByNama(ctx, req.(*ReadKategoriObatByNamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KategoriObatService_ReadKategoriObat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KategoriObatServiceServer).ReadKategoriObat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KategoriObatService/ReadKategoriObat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KategoriObatServiceServer).ReadKategoriObat(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KategoriObatService_UpdateKategoriObat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKategoriObatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KategoriObatServiceServer).UpdateKategoriObat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KategoriObatService/UpdateKategoriObat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KategoriObatServiceServer).UpdateKategoriObat(ctx, req.(*UpdateKategoriObatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KategoriObatService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.KategoriObatService",
	HandlerType: (*KategoriObatServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddKategoriObat",
			Handler:    _KategoriObatService_AddKategoriObat_Handler,
		},
		{
			MethodName: "ReadKategoriObatByNama",
			Handler:    _KategoriObatService_ReadKategoriObatByNama_Handler,
		},
		{
			MethodName: "ReadKategoriObat",
			Handler:    _KategoriObatService_ReadKategoriObat_Handler,
		},
		{
			MethodName: "UpdateKategoriObat",
			Handler:    _KategoriObatService_UpdateKategoriObat_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "kategori_obat.proto",
}

func init() { proto.RegisterFile("kategori_obat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0xd5, 0xf8, 0xf1, 0xf4, 0xbe, 0x85, 0x72, 0x7d, 0x4f, 0xe6, 0xc5, 0x07, 0x95, 0xac, 0xa4,
	0x8b, 0x08, 0xf6, 0x17, 0xd4, 0x56, 0x5a, 0x2a, 0x34, 0x10, 0xe9, 0xb2, 0x94, 0x89, 0x99, 0x86,
	0xa0, 0x26, 0x31, 0x19, 0x0b, 0xf9, 0x5b, 0x85, 0x6e, 0xfa, 0x33, 0xfa, 0x8b, 0x4a, 0x32, 0x51,
	0x63, 0x34, 0xb6, 0xdd, 0xbb, 0x9c, 0x73, 0xee, 0x3d, 0xcc, 0x9c, 0x73, 0xe7, 0x42, 0x6b, 0x46,
	0x39, 0xb3, 0x5c, 0xdf, 0x7e, 0x72, 0x0d, 0xca, 0x55, 0xcf, 0x77, 0xb9, 0x8b, 0x65, 0xcb, 0xf7,
	0xa6, 0x72, 0xc7, 0x72, 0x5d, 0x6b, 0xce, 0xfa, 0x31, 0x66, 0xac, 0x9e, 0xfb, 0x6c, 0xe1, 0xf1,
	0x50, 0x94, 0x28, 0xaf, 0x12, 0xe0, 0xa5, 0x69, 0x8e, 0x93, 0x6e, 0xcd, 0xa0, 0x5c, 0x67, 0x4b,
	0x3c, 0x87, 0xe6, 0xd8, 0x35, 0x59, 0x1a, 0x26, 0xc5, 0x6e, 0xb1, 0x57, 0xd7, 0xf7, 0xf0, 0xa8,
	0xf6, 0x9e, 0x2e, 0xe8, 0x4e, 0xad, 0x24, 0x6a, 0xb3, 0x38, 0xfe, 0x87, 0xfa, 0x35, 0x0b, 0x66,
	0xbe, 0xed, 0x05, 0x36, 0x29, 0xc5, 0x45, 0x5b, 0x00, 0x65, 0xa8, 0x45, 0xea, 0xb1, 0x42, 0x39,
	0x26, 0x37, 0xe7, 0xa8, 0xf3, 0xca, 0x67, 0x94, 0x33, 0x73, 0x18, 0x92, 0x8a, 0xe8, 0xdc, 0x00,
	0x29, 0x56, 0x73, 0x48, 0x75, 0x87, 0xd5, 0x9c, 0x48, 0xf7, 0xc1, 0x33, 0x29, 0x67, 0xc3, 0x90,
	0xfc, 0x12, 0xba, 0xeb, 0xf3, 0x96, 0xd3, 0x1c, 0x52, 0x4b, 0x73, 0x9a, 0x83, 0x6d, 0xa8, 0x4e,
	0x38, 0xe5, 0xab, 0x80, 0xd4, 0xbb, 0xc5, 0x5e, 0x45, 0x4f, 0x4e, 0xca, 0x0d, 0xfc, 0xd3, 0x19,
	0xdd, 0x31, 0x6d, 0x18, 0x46, 0x6f, 0x4d, 0xac, 0xfb, 0xae, 0x1d, 0xca, 0xbb, 0x04, 0x72, 0x9e,
	0x52, 0xe0, 0x9d, 0x52, 0x38, 0x9a, 0x82, 0x01, 0x7f, 0xb2, 0xde, 0xc5, 0xae, 0xdd, 0x41, 0x83,
	0xce, 0xe7, 0x19, 0xd3, 0x4a, 0xbd, 0xdf, 0x83, 0xae, 0x1a, 0xfd, 0x07, 0x35, 0xdf, 0x70, 0x3d,
	0xdb, 0xa8, 0xbc, 0x49, 0xf0, 0x57, 0x5c, 0xe4, 0xf4, 0x43, 0x7e, 0x90, 0xcd, 0xe0, 0x43, 0x82,
	0x56, 0xfa, 0x59, 0x13, 0xe6, 0xbf, 0xd8, 0x53, 0x86, 0x23, 0x68, 0x64, 0xb6, 0x0d, 0x12, 0x91,
	0xca, 0xfe, 0x12, 0x92, 0xdb, 0xaa, 0xd8, 0x5c, 0xea, 0x7a, 0x73, 0xa9, 0xa3, 0x68, 0x73, 0x29,
	0x05, 0x7c, 0x84, 0xf6, 0xe1, 0x14, 0xf1, 0xec, 0x78, 0xc6, 0x4b, 0xf9, 0xcb, 0x21, 0x50, 0x0a,
	0x78, 0x0b, 0xcd, 0x2c, 0x8f, 0x39, 0x97, 0x91, 0xe5, 0xc3, 0x7a, 0x89, 0xd2, 0x18, 0x70, 0x7f,
	0x7c, 0xb0, 0x23, 0x7a, 0x0e, 0x0e, 0x56, 0xfe, 0xab, 0x8d, 0x6a, 0x8c, 0x5c, 0x7c, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x1c, 0x59, 0x8d, 0xec, 0x05, 0x00, 0x00,
}
